//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU|Make|Model|Year|Submodel|ourBodyTypeName|_BodyNumDoors_|Universal SKU|SKU_Naumkin|Required SKU|Optional SKU|Available|Available1|ourMake|Fitment_note|ourRealModel|_MfrBodyCodeName_|ourModel|Available2|Processing|Brand|_BodyTypeName_|Part#1|NumDoor|Length_b|MMY
        ///C0789CC-GB|Chevrolet|Silverado 1500|2007|||||C0789CC-GB|||||Chevy||||||True|RBP®|Crew Cab Pickup|C0789CC-GB||5&apos;6&quot; Bed|
        ///C0789CC-GB|Chevrolet|Silverado 1500|2008|||||C0789CC-GB|||||Chevy||||||True|RBP®|Crew Cab Pickup|C0789CC-GB||5&apos;6&quot; Bed|
        ///C0789C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Fitments {
            get {
                return ResourceManager.GetString("Fitments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU|CORE DEPOSIT|CF SHIPPING|SBOX|Available|BRANDNAME|PACKAGE|SHIPPINGTYPE|Templates|forname1|forname2|Core|Valid|Price|Height|Length|Width|Weight|UPC|DATA SOURCE|IN STOCK|MainProduct|VENDORID
        ///117.42043|||||Centric®|||Centric Disc Brake Hardware||Disc Brake Hardware||True|10.58|2.00|9.00|6.00|0.50|805890380016|||M|
        ///117.43006|||||Centric®|||Centric Disc Brake Hardware||Disc Brake Hardware||True|12.64|2.00|9.00|6.00|0.20|805890099840|||M|
        ///117.43007|||||Centric®|||Centric Disc Brake Hardware||Disc Brake Har [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
    }
}
